parameters:
    logger_database.class: ACSEO\Bundle\BaseRestBundle\Logger\DatabaseHandler

# services:
#   ACSEO.listener.logrequest:
#     class: ACSEO\Bundle\BaseRestBundle\Listener\LogRequestListener
#     arguments: [ @service_container ]
#     tags:
#       - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }


services:
    # monolog.processor.request:
    #     class: ACSEO\Bundle\BaseRestBundle\Processor\RequestProcessor
    #     arguments:  [ @service_container ]
    #     tags:
    #         - { name: monolog.processor, method: processRecord }
    #         - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest}

    # logger_database:
    #     class: %logger_database.class%
    #     calls:
    #         - [ setContainer, [ @service_container ] ]

    # tools.backtrace_logger_listener:
    #     class: ACSEO\Bundle\BaseRestBundle\Listener\BacktraceLoggerListener
    #     tags:
    #         - {name: "monolog.logger", channel: "backtrace"}
    #         - {name: "kernel.event_listener", event: "kernel.exception", method: "onKernelException"}
    #     arguments:
    #         - @logger
