<?php

namespace ACSEO\Bundle\BaseRestBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BaseRestEntityRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRestEntityRepository extends EntityRepository
{
    public function findByQuery(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        $query = $this->getQuery($criteria);
        $query = $this->setOrderBy($query, $orderBy);
        $query = $this->setLimit($query, $limit);
        $query = $this->setOffset($query, $offset);

        return $query;
    }

    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        return $this->findByQuery($criteria, $orderBy, $limit, $offset)->getQuery()->getResult();
    }

    public function getQuery($criteria)
    {
        $query = $this->createQueryBuilder('tb');
        foreach ($criteria as $paramKey => $paramValue) {
            $query->andWhere(sprintf('tb.%s = :%s', $paramKey, $paramKey))->setParameter($paramKey, $paramValue);
        }

        return $query;
    }

    public function setOrderBy($query, $orderBy)
    {
        if ($orderBy != null) {
            reset($orderBy);
            $query->orderBy(sprintf('tb.%s', key($orderBy)), current($orderBy));
        }

        return $query;
    }
    public function setLimit($query, $limit)
    {
        if ($limit !== false) {
            $query->setMaxResults($limit);
        }

        return $query;
    }
    public function setOffset($query, $offset)
    {
        if ($offset !== false) {
            $query->setFirstResult($offset);
        }

        return $query;
    }
}
